name: 'Pull request workflow with Slack'
description: 'It creates a workflow for your pull request by auto-assigning reviewers and sending slack notifications as a thread'
author: 'cakarci <salihcakarci@gmail.com>'
inputs:
  github-token:
    required: true
    description: 'Github token'
  slack-token:
    required: true
    description: 'Slack token'
  slack-channel-id:
    required: true
    description: 'Slack channel id for the notifications'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'
