#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
cd ..
IS_DIST_CHANGED=$(git --no-pager diff .husky)
# shellcheck disable=SC2039
if [[ ("$IS_DIST_CHANGED" =~ (^diff --git+)) ]]
then
  echo "changed $(pwd)"
  git add dist
  git commit -m "chore: update dist folder"
else
  echo "not changed $(pwd)"
fi

